<template><div><div class="language-vb line-numbers-mode" data-ext="vb" data-title="vb"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Worksheet_SelectionChange</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ByVal</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Target </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">As</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> Range</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Call </span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">gys</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="自动筛选" tabindex="-1"><a class="header-anchor" href="#自动筛选"><span>自动筛选</span></a></h2>
<div class="language-vb line-numbers-mode" data-ext="vb" data-title="vb"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Worksheet_Change</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ByVal</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Target </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">As</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> Range</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">Application</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">EnableEvents</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> False</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Call </span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">shaixuan</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">Application</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">EnableEvents</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> True</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="自动更新" tabindex="-1"><a class="header-anchor" href="#自动更新"><span>自动更新</span></a></h2>
<div class="language-vb line-numbers-mode" data-ext="vb" data-title="vb"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Worksheet_Activate</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ActiveWorkbook.RefreshAll</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="数据备份" tabindex="-1"><a class="header-anchor" href="#数据备份"><span>数据备份</span></a></h2>
<div class="language-vb line-numbers-mode" data-ext="vb" data-title="vb"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Workbook_BeforeSave</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ByVal</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> SaveAsUI </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">As</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> Boolean</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">,</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Cancel</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> As</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> Boolean</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ThisWorkbook.SaveCopyAs </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">d:\data\</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> &#x26;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Format</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">Now</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">, </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">yyyymmddhhmmss</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> &#x26;</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">.xls</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="其他对象事件" tabindex="-1"><a class="header-anchor" href="#其他对象事件"><span>其他对象事件</span></a></h2>
<div class="language-vb line-numbers-mode" data-ext="vb" data-title="vb"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">CommandButton1_Click</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">MsgBox</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">点我干嘛</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


