<template><div><h2 id="窗体" tabindex="-1"><a class="header-anchor" href="#窗体"><span>窗体</span></a></h2>
<div class="language-vb line-numbers-mode" data-ext="vb" data-title="vb"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">UserForm_Activate</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">Application</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Visible</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> False</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">UserForm_Click</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">UserForm_QueryClose</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Cancel</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> As</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> Integer</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">,</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> CloseMode</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> As</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> Integer</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">Application</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.Quit</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="文本框控件" tabindex="-1"><a class="header-anchor" href="#文本框控件"><span>文本框控件</span></a></h2>
<div class="language-vb line-numbers-mode" data-ext="vb" data-title="vb"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Private Sub </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">CommandButton1_Click</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">If</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> UserForm1.TextBox1.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Value</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">张三</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> And</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> UserForm1.TextBox2.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Value</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">123</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> Then</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    Sheet2.Unprotect Password:</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">test</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    Sheet2.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Visible</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> xlSheetVisible</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    Me.Hide</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">ElseIf</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> UserForm1.TextBox1.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Value</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">李四</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> And</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> UserForm1.TextBox2.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Value</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">0000</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> Then</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    Sheet3.Unprotect Password:</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">test</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    Sheet3.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Visible</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> xlSheetVisible</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    Me.Hide</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">End If</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="组合框控件" tabindex="-1"><a class="header-anchor" href="#组合框控件"><span>组合框控件</span></a></h2>
<div class="language-vb line-numbers-mode" data-ext="vb" data-title="vb"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">'增加下拉框的选项</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Sub</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> test1</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">UserForm1.ComboBox1.AddItem </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">苏州</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">'把单元格一列数据设置为下拉的数据源</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Sub</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> test2</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">For</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> i</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> To</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 6</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    UserForm1.ComboBox1.AddItem Sheet1.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Range</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">a</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> &#x26;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> i</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">Next</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">'删除掉下拉框里的一项</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Sub</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> test3</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Call </span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">test2</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">UserForm1.ComboBox1.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">RemoveItem</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> (</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> '删除第二项</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">'清空下拉框数据源</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Sub</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> test4</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Call </span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">test2</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">UserForm1.ComboBox1.</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">Clear</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">'计算下拉框里有多少个选项</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Sub</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> test5</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Call </span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">test2</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">MsgBox</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> UserForm1.ComboBox1.ListCount</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">'把下拉框数据源里某个值输出到单元格</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Sub</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> test6</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Call </span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">test2</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Range</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">c2</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> UserForm1.ComboBox1.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">List</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">'把下拉框里所有的选项输出到单元格区域</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Sub</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> test7</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">Call </span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">test2</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Range</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">d1:d5</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> UserForm1.ComboBox1.List</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">End Sub</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


